#!/bin/bash

# print every other line from the input
counter=1
while read line
do
    if [ $((counter % 2)) -eq 1 ]
    then
        echo "$line"
    fi
    counter=$((counter + 1))
done < "${1:-/dev/stdin}"

